# Generated by Django 4.2.7 on 2025-10-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
